# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
 - title: Gemini 3.1 Pro
   provider: gemini
   model: gemini-3.1-pro
   apiKey: AIzaSyCYgk8mbFK4FJ2y59UElRepPj19Bz4xVY8
 - uses: google/gemini-3.1-pro-preview
   with:
      GEMINI_API_KEY: AIzaSyCYgk8mbFK4FJ2y59UElRepPj19Bz4xVY8
 - uses: google/gemini-3-flash-preview
   with:
      GEMINI_API_KEY: AIzaSyCYgk8mbFK4FJ2y59UElRepPj19Bz4xVY8
# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
# mcpServers:
#   - uses: anthropic/memory-mcp
